machine qemu

module usb-storage
module isofs
module udf
module vfat
module ext4

package autonet
package netfiles

package xorg7-vesa
package locale-en_US
package fonts-TTF-BH

package vncviewer

param bootlogo false
param splash silent
param fastboot true
param basename thinstation
param basepath thinstation
